# Generated by Django 2.2.16 on 2022-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin'), (4, 'superuser')], help_text='User role', verbose_name='User role'),
        ),
    ]
