# Generated by Django 2.2.16 on 2022-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220531_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin'), (4, 'superuser')], help_text='User role', null=True, verbose_name='User role'),
        ),
    ]
