# Generated by Django 2.2.16 on 2022-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220531_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='Пользователь', help_text='Describes users permissions', max_length=20, verbose_name='User role'),
        ),
    ]
