# Generated by Django 2.2.16 on 2022-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220531_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
