# Generated by Django 2.2.16 on 2022-06-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='slug',
        ),
    ]
