# Generated by Django 2.2.16 on 2022-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_remove_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title', to='titles.Genre', verbose_name='Жанр'),
        ),
    ]
