# Generated by Django 2.2.16 on 2022-06-05 13:43

from django.db import migrations, models
import titles.models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20220601_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Заголовок', 'verbose_name_plural': 'Заголовки'},
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='titles.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, validators=[titles.models.Title.year_validation]),
        ),
    ]
